### ISSUE TITLE
unexpected fault address 0x0 in exago.io

### ISSUE THREAD

**Issue by mewmew** [exago/app#7]
I tried to find the backend repository for Exago but was unable to. Thus reporting this issue to the front-end repo. Is the backend of Exago open source or intended to be in the future?

From https://www.exago.io/project/github.com/mewkiz/flac

```
Something went wrong.

unexpected fault address 0x0
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x80 addr=0x0 pc=0x74270b]

goroutine 30 [running]:
runtime.throw(0x844b07, 0x5)
	/var/task/exago/go-1.7.4/bin/linux-amd64/goroot/src/runtime/panic.go:566 +0x95 fp=0xc420051370 sp=0xc420051350
runtime.sigpanic()
	/var/task/exago/go-1.7.4/bin/linux-amd64/goroot/src/runtime/sigpanic_unix.go:27 +0x288 fp=0xc4200513c8 sp=0xc420051370
crypto/elliptic.p256MovCond(0x7ff40acb6cd8, 0xc, 0xc, 0x7ff40acb6cd8, 0xc, 0xc, 0x7ff40acb6538, 0xc, 0xc, 0x1, ...)
	/var/task/exago/go-1.7.4/bin/linux-amd64/goroot/src/crypto/elliptic/p256_asm_amd64.s:84 +0x2b fp=0xc4200513d0 sp=0xc4200513c8
crypto/elliptic.(*p256Point).p256ScalarMult(0x7ff40acb6538, 0xc4200514c8, 0x4, 0x4)
	/var/task/exago/go-1.7.4/bin/linux-amd64/goroot/src/crypto/elliptic/p256_amd64.go:537 +0xc28 fp=0xc420051480 sp=0xc4200513d0
crypto/elliptic.p256Curve.CombinedMult(0x7ff40bf5a4d8, 0x7ff40bf5aed0, 0x7ff40bf5af30, 0x7ff40acb6498, 0x20, 0x20, 0x7ff40acb64b8, 0x20, 0x20, 0x0, ...)
	/var/task/exago/go-1.7.4/bin/linux-amd64/goroot/src/crypto/elliptic/p256_amd64.go:230 +0x309 fp=0xc420051510 sp=0xc420051480
crypto/ecdsa.Verify(0x7ff40bf5b4a0, 0x7ff40acb5dc0, 0x30, 0x30, 0x7ff40acb5e30, 0x7ff40acb5ea8, 0x0)
	/var/task/exago/go-1.7.4/bin/linux-amd64/goroot/src/crypto/ecdsa/ecdsa.go:255 +0x3cd fp=0xc420051630 sp=0xc420051510
crypto/tls.(*ecdheKeyAgreement).processServerKeyExchange(0x7ff40acb5530, 0x7ff40b91b088, 0x7ff40b91b628, 0x7ff40bf54db0, 0x7ff40bf59ce8, 0x7ff40acb5458, 0x0, 0xa2a440)
	/var/task/exago/go-1.7.4/bin/linux-amd64/goroot/src/crypto/tls/key_agreement.go:366 +0x745 fp=0xc420051770 sp=0xc420051630
crypto/tls.(*clientHandshakeState).doFullHandshake(0xc420051e08, 0x7ff40bf54e80, 0x66)
	/var/task/exago/go-1.7.4/bin/linux-amd64/goroot/src/crypto/tls/handshake_client.go:356 +0x31d fp=0xc420051bf0 sp=0xc420051770
crypto/tls.(*Conn).clientHandshake(0x7ff40b91b1d0, 0x88edf8, 0x7ff40b91b2d8)
	/var/task/exago/go-1.7.4/bin/linux-amd64/goroot/src/crypto/tls/handshake_client.go:228 +0xfd1 fp=0xc420051ec0 sp=0xc420051bf0
crypto/tls.(*Conn).Handshake(0x7ff40b91b1d0, 0x0, 0x0)
	/var/task/exago/go-1.7.4/bin/linux-amd64/goroot/src/crypto/tls/conn.go:1260 +0x1b8 fp=0xc420051f30 sp=0xc420051ec0
net/http.(*Transport).dialConn.func3(0x7ff40b91b1d0, 0x7ff40b91b590, 0x7ff40b91b500)
	/var/task/exago/go-1.7.4/bin/linux-amd64/goroot/src/net/http/transport.go:1033 +0x2f fp=0xc420051f78 sp=0xc420051f30
runtime.goexit()
	/var/task/exago/go-1.7.4/bin/linux-amd64/goroot/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc420051f80 sp=0xc420051f78
created by net/http.(*Transport).dialConn
	/var/task/exago/go-1.7.4/bin/linux-amd64/goroot/src/net/http/transport.go:1038 +0xb4f

goroutine 1 [select]:
net/http.(*Transport).getConn(0x7ff40d0a4340, 0x7ff40b912870, 0x0, 0x7ff40b9121c0, 0x5, 0x7ff40b912890, 0xe, 0x0, 0x0, 0x18)
	/var/task/exago/go-1.7.4/bin/linux-amd64/goroot/src/net/http/transport.go:890 +0x9d2
net/http.(*Transport).RoundTrip(0x7ff40d0a4340, 0x7ff40b912298, 0x7ff40d0a4340, 0x0, 0x7ff400000000)
	/var/task/exago/go-1.7.4/bin/linux-amd64/goroot/src/net/http/transport.go:367 +0x307
net/http.send(0x7ff40b912298, 0xa02600, 0x7ff40d0a4340, 0x0, 0x0, 0x0, 0x8, 0xc420070d70, 0x7ff40b9123d0)
	/var/task/exago/go-1.7.4/bin/linux-amd64/goroot/src/net/http/client.go:256 +0x15f
net/http.(*Client).send(0xa2a220, 0x7ff40b912298, 0x0, 0x0, 0x0, 0x7ff40b9123d0, 0x0, 0x1)
	/var/task/exago/go-1.7.4/bin/linux-amd64/goroot/src/net/http/client.go:146 +0x102
net/http.(*Client).doFollowingRedirects(0xa2a220, 0x7ff40b912298, 0x88e898, 0x28, 0x0, 0x0)
	/var/task/exago/go-1.7.4/bin/linux-amd64/goroot/src/net/http/client.go:528 +0x5e5
net/http.(*Client).Get(0xa2a220, 0x7ff40b9121c0, 0x28, 0x0, 0x0, 0x7ff40c2026c1)
	/var/task/exago/go-1.7.4/bin/linux-amd64/goroot/src/net/http/client.go:418 +0x93
main.httpsOrHTTP.func1(0x844b7a, 0x5, 0x1, 0xc420071060, 0x54bbb9, 0x7ff40c2026c1, 0xa)
	/var/task/exago/go-1.7.4/bin/linux-amd64/goroot/src/cmd/go/http.go:86 +0x130
main.httpsOrHTTP(0x7ff40c2026c1, 0x17, 0x0, 0x1, 0x1, 0x7ff40b912080, 0x0, 0x1, 0x0)
	/var/task/exago/go-1.7.4/bin/linux-amd64/goroot/src/cmd/go/http.go:95 +0xaa
main.repoRootForImportDynamic(0x7ff40c2026c1, 0x17, 0x0, 0x0, 0x0, 0x0)
	/var/task/exago/go-1.7.4/bin/linux-amd64/goroot/src/cmd/go/vcs.go:708 +0x13f
main.repoRootForImportPath(0x7ff40c2026c1, 0x17, 0x0, 0x7ff40b976560, 0x0, 0x7ff40b976f60)
	/var/task/exago/go-1.7.4/bin/linux-amd64/goroot/src/cmd/go/vcs.go:599 +0x40b
main.downloadPackage(0x7ff40c192518, 0x7ff40d0abf58, 0xc4200719b8)
	/var/task/exago/go-1.7.4/bin/linux-amd64/goroot/src/cmd/go/get.go:385 +0x15ad
main.download(0x7ff40c2026c1, 0x17, 0x7ff40c1fdd10, 0x7ff40d087868, 0x0)
	/var/task/exago/go-1.7.4/bin/linux-amd64/goroot/src/cmd/go/get.go:237 +0xbf0
main.download(0x7fff30b6da10, 0x1a, 0x0, 0x7ff40d087868, 0x2)
	/var/task/exago/go-1.7.4/bin/linux-amd64/goroot/src/cmd/go/get.go:309 +0x361
main.runGet(0xa23620, 0x7ff40d0d2600, 0x1, 0x1)
	/var/task/exago/go-1.7.4/bin/linux-amd64/goroot/src/cmd/go/get.go:111 +0x145
main.main()
	/var/task/exago/go-1.7.4/bin/linux-amd64/goroot/src/cmd/go/main.go:181 +0x624

goroutine 4 [syscall]:
os/signal.signal_recv(0x0)
	/var/task/exago/go-1.7.4/bin/linux-amd64/goroot/src/runtime/sigqueue.go:116 +0x157
os/signal.loop()
	/var/task/exago/go-1.7.4/bin/linux-amd64/goroot/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.1
	/var/task/exago/go-1.7.4/bin/linux-amd64/goroot/src/os/signal/signal_unix.go:28 +0x41

goroutine 25 [chan receive]:
net/http.(*Transport).dialConn(0x7ff40d0a4340, 0xa07f00, 0x7ff40d0e85b0, 0x0, 0x7ff40b9121c0, 0x5, 0x7ff40b912890, 0xe, 0x0, 0x0, ...)
	/var/task/exago/go-1.7.4/bin/linux-amd64/goroot/src/net/http/transport.go:1039 +0xb91
net/http.(*Transport).getConn.func4(0x7ff40d0a4340, 0xa07f00, 0x7ff40d0e85b0, 0x7ff40b9128a0, 0x7ff40b9128d0)
	/var/task/exago/go-1.7.4/bin/linux-amd64/goroot/src/net/http/transport.go:885 +0x78
created by net/http.(*Transport).getConn
	/var/task/exago/go-1.7.4/bin/linux-amd64/goroot/src/net/http/transport.go:887 +0x398
```

**Comment by jgautheron** [comment]
Hi @mewmew thanks for reporting.
The backend repo will be open sourced, we just want to make it a bit more "contribution-friendly" before releasing it.
Very interesting error we'll take a look!

**Comment by mewmew** [comment]
@jgautheron Lovely to hear! Happy hacking : )
